---
timezone: "UTC"
wp_docroot: "/var/www/html"
wp_domain: "example.com"
php_version: "8.1"
php_fpm_service: "php{{ php_version }}-fpm"
php_fpm_socket: "/run/php/php{{ php_version }}-fpm.sock"
wp_site_url: "https://example.com"
wp_backup_archive_path: "/tmp/wp-content.tar.gz"
wp_db_dump_path: "/tmp/wordpress.sql.gz"
wp_backup_bucket: "my-wordpress-backups"
